### ISSUE TITLE
Allow the error message to be on the first line

### ISSUE THREAD

**Issue by mirelon** [dekellum/rjack#7]
Now, the error message looks like this:

    [23/Jan/2015 18:28:52][ERROR] Exception:
    MyError: My custom error message
        /path/to/the/project/some_class.rb:47:in `initialize'

For parsing options, it could be better to have the error message on the first line. Or at least make it customizable.

    [23/Jan/2015 18:28:52][ERROR] Exception: MyError: My custom error message
        /path/to/the/project/some_class.rb:47:in `initialize'

**Comment by slaw-ik** [comment]
+1

**Comment by dekellum** [comment]
By "Now" are you implying this is a change or regression in rjack-slf4j?  If so, what versions? Or do you mean now that you are logging an exception from Ruby (using rjack-slf4j) instead of Java?

I think I originally added a `\n` as a perceived formatting improvement: shorter line widths, less line wrap in console.  Have I taken too great a liberty? Since this is the first I've heard issue: What parsing does this interfere with specifically?

**Comment by mirelon** [comment]
We managed to have the exception message on the first line by simply implementing custom string representation of the exception.
So I will close the issue.

**Comment by dekellum** [comment]
In the act of looking into to this I found some related issues. Releases rjack-slf4j-1.7.10.0 and rjack-logback-1.7.2 might be of interest.
